### PR TITLE
Added formatquiz and theorem bubbles

### PR DESCRIPTION
**Pull request by FunByJohn**
* Added init.py which initializes js and css folders if they don't exist
* Added formatquiz (Current documentation in danish: http://funbyjohn.com/digitaliseringAfLinAlg/environments/Chapters/formatquiz.html )
* Added theorem bubble, which lets you preview a theorem (and other environments) when you hover your mouse over for example Theorem 4.16. Also works for equation numbers. I still need to add functionality for referencing equations in other chapters
* Other fixes

### CODE REVIEW

**Comment by nielsthl** [comment]
`Notes/IMO21/Makefile` is incomplete. Also, `\includehtml{bubble}` needs (among other things) to be added to `imodefs`. When this is done there are problems with the marked text of footnotes (below: compute y y etc) containing KaTeX:

footnotesIMO21

**Comment by nielsthl** [comment]
In general popups display nicely. There are sometimes issues with popups for equations like in Chapter 6 (comvexfunctions.tex) of Notes/IMO21:

IMO21popup

Here the popup window for (6.7) is far from wide enough to display the math.

**Comment by nielsthl** [comment]
Popups from a different chapter need to be handled (we know that). Currently the popup window is showing `Loading...`

**Comment by FunByJohn** [comment]
Fixed Makefile stuff.

Line 210 in the previous version of `bubble.js` was part of a scheme to detect whether the label of the footnote was more than 1 line long. If it is more than 1 line long, it's hard to find out how large the bounding box of the footnote label is, and therefore hard to find out where to place the bubble so it looks good. Therefore I tried the following hack: Put each word into its own `<span>` tag, and then find the `<span>` tag closest to the mouse, and place the bubble there. This however messed up with the KaTeX.

My fix: I removed the trick, and now instead I detect if the bubble is about to placed too far to the left, or too far to the right, and if this is the case, we probably have more than 1 line of text, and then we just place the bubble where the user's cursor is. The logic is just lines 68-77 in the new `bubble.js`:
```
var targetX = Math.round(bubbleLabel.offsetLeft + bubbleLabel.offsetWidth / 2);
    var targetY = Math.round(bubbleLabel.offsetTop);

    if (targetX < 0.1 * window.innerWidth || 0.9 * window.innerWidth < targetX) {
        // If the bubble appears top far to the left or right, we simply locate it where the user had
        // their cursor. This will help us avoid the bubble appearing at a weird location if the footnote
        // label spans multiple lines.
        targetX = bubbleMouseX;
        targetY = bubbleMouseY - 5;
    }
```

Next up I will look at making the bubble scroll if there is x overflow (the problem in `convexfunctions.tex`)

**Comment by FunByJohn** [comment]
* Fixed the x-overflow problem in bubble.
* Added equations from other chapters to bubble (Try this out in IMO21 chapter 8, search for "(7.8)").

Remember to run the book in localhost (or on a website) for bubbles referencing other chapters to work (just like how you need to do when you want to use the search feature). This can be done using the command
```
python3 -m http.server
```
in the same folder as your book.

**Review by nielsthl — APPROVED** [review]
Popups from other chapters and x-overflow seem to work fine. There is one exception though: sage environments do not show in popups. In IMO21, Chapter 4, the reference to Example 4.32 in Exercise 4.35 illustrates this. This is currently a minor issue.

**Pull request merged**
